M48
; DRILL file KiCad 10.0.5 date 2026-09-04T21:38:02
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-09-04T21:38:02+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X1.7449Y-2.7392
X1.7449Y-2.9667
T2
X4.4867Y-2.0722
M30
